[workspace]
members = [
    "crates/plainfeed-core",
    "crates/plainfeed-git",
    "crates/plainfeed-server",
    "crates/plainfeed-service",
    "crates/plainfeed-sync",
    "crates/plainfeed-sync-core",
    "experiments/wasmtime-run-service",
]
exclude = ["refs/gitoxide", "refs/memmap2", "refs/reqwest"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/enbop/plainfeed"

[workspace.dependencies]
plainfeed-core = { path = "crates/plainfeed-core" }
plainfeed-git = { path = "crates/plainfeed-git" }
plainfeed-sync = { path = "crates/plainfeed-sync" }
plainfeed-sync-core = { path = "crates/plainfeed-sync-core" }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
time = { version = "0.3.44", features = ["formatting", "parsing"] }
toml = "0.9.8"

[patch.crates-io]
memmap2 = { git = "https://github.com/enbop/memmap2-rs.git", rev = "7163e105159cb9e95d952e42d390e36ccd83e5c1" }
