[package]
name = "plainfeed-sync"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
plainfeed-core.workspace = true
plainfeed-git.workspace = true
plainfeed-sync-core.workspace = true
rustls-rustcrypto = "0.0.2-alpha"
thiserror.workspace = true
time.workspace = true
tokio = { version = "1.52.3", features = ["net", "rt", "time"] }

[dev-dependencies]
gix = { path = "../../refs/gitoxide/gix", default-features = false, features = ["index", "sha1", "tree-editor"] }
tempfile = "3.23.0"
