[package]
name = "plainfeed-gix-wasi-probe"
version = "0.0.0"
edition = "2024"
publish = false

[features]
default = ["local"]
local = ["gix/status", "gix/sha1", "gix/tree-editor"]
network = ["gix/blocking-network-client"]
https-reqwest-rustls = ["network", "gix/blocking-http-transport-reqwest-rust-tls"]

[dependencies]
gix = { version = "0.85.0", default-features = false }
